// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/routercore/wireless"
)

// Injectors from inject.go:

// New creates a new service implementation.
func NewService(i *wireless.Injector) (*Service, func(), error) {
	logger := NewLogger()
	config, err := ConfigInject(i)
	if err != nil {
		return nil, nil, err
	}
	service := &Service{
		log: logger,
		cfg: config,
	}
	return service, func() {
	}, nil
}

// inject.go:

func ConfigInject(i *wireless.Injector) (*Config, error) {
	var c *Config = &Config{}
	err := i.InjectAs(&c)
	return c, err
}
